=== szkiba/configen/cmd/configen/testdata/values.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "required": ["domain", "tenant", "aliases", "services"],
  "properties": {
    "domain": {
      "type": "string"
    },
    "tenant": {
      "type": "string"
    },
    "aliases": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "services": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["name", "template"],
        "properties": {
          "name": {
            "type": "string"
          },
          "scope": {
            "type": "string"
          },
          "template": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== szkiba/configen/cmd/configen/testdata/values.json
{
  "$schema": "./values.schema.json",
  "domain": "example.com",
  "tenant": "playground",
  "aliases": ["play-field", "sandbox"],
  "services": [
    {
      "name": "search",
      "template": "https://places.foo.test"
    },
    {
      "name": "register",
      "scope": "bar",
      "template": "https://users.bar.test"
    }
  ]
}
